// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAceO4oK-64lqWmc9Jpq-DjLvgq5ZAHwAY',
    appId: '1:754427206411:web:6354a9e5de8ba4479ae00e',
    messagingSenderId: '754427206411',
    projectId: 'aura-kart',
    authDomain: 'aura-kart.firebaseapp.com',
    storageBucket: 'aura-kart.firebasestorage.app',
    measurementId: 'G-78LM6XFZTK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBappFRRaCsnVpDjmtq92Si2qZx3NAJSNc',
    appId: '1:754427206411:android:bccd4a7c3dfdc0119ae00e',
    messagingSenderId: '754427206411',
    projectId: 'aura-kart',
    storageBucket: 'aura-kart.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAkjPUiwr4PU4K1_hZ6ShDQnKCsXDeFB20',
    appId: '1:754427206411:ios:5c420f230d8ed6a39ae00e',
    messagingSenderId: '754427206411',
    projectId: 'aura-kart',
    storageBucket: 'aura-kart.firebasestorage.app',
    androidClientId: '754427206411-2gnooaid0n6t7dg8bhgs9telsbap4pne.apps.googleusercontent.com',
    iosClientId: '754427206411-6k3vqkbi9011r9mmq42o9mksjf9e8gs9.apps.googleusercontent.com',
    iosBundleId: 'com.example.auraKartAdminPanel',
  );

}